bootstrapScript: |
  #!/bin/bash
  apt-get update && apt-get install -y build-essential
  pip install psycopg2==2.9.6 \
    sqlalchemy-bigquery==1.6.1 \
    prophet==1.1.6 \
    elasticsearch-dbapi==0.2.5 &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
configOverrides:
  enable_proxy_fix: |
    ENABLE_PROXY_FIX = True
  feature_flags: |
    FEATURE_FLAGS = {
      "DYNAMIC_PLUGINS": True,
      "DASHBOARD_NATIVE_FILTERS": True
    }
  secret: |
    SECRET_KEY = 'MUDSHARK'
extraEnv:
  SMTP_HOST: smtp.gmail.com
  SMTP_MAIL_FROM: your_email@gmail.com
  SMTP_PORT: "587"
  SMTP_USER: jconlon62@gmail.com
extraSecretEnv:
  SMTP_PASSWORD: YourEmailPassword
image:
  repository: apache/superset
ingress:
  annotations:
    ingressClassName: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  enabled: true
  hosts:
  - superset.local
  path: /
  tls:
  - hosts:
    - superset.local
    secretName: superset-tls
init:
  loadExamples: true
initImage:
  repository: apache/superset
postgresql:
  enabled: true
  postgresqlPassword: mySecurePassword
redis:
  enabled: true
  password: myRedisPassword
supersetCeleryBeat:
  enabled: true
supersetNode:
  replicaCount: 2
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1Gi
supersetWorker:
  replicaCount: 2
