# openebs-app.yaml (in argocd namespace)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://openebs.github.io/openebs
    chart: openebs
    targetRevision: openebs-4.1.1
    helm:
      valuesFiles:
      - helm-values/openebs-custom-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

